version: '3.8'
services:
  mywebserver:
    image: httpd
    ports:
      - 80:80
    depends_on:
      - mydb
  mydb:
    image: mysql
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=Pass123!
  admindb:
    image: adminer
    ports:
      - 8080:8080
    depends_on:
      - mydb