---
- hosts: serverapache2
  become: yes
  tasks:
    - name: 'apt-get update'
      apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: 'install docker'
      apt:
        name: docker-ce
        state: present
    
    - name: 'start docker'
      service:
        name: docker
        state: started

    - name: 'create directory'
      file:
        path: /home/parallels/exercice3
        state: directory
        owner: parallels 
        group: parallels 
        mode: 0755
      
    - name: 'copy dockerfile'
      copy:
        src: Dockerfile
        dest: /home/parallels/exercice3/Dockerfile
        owner: parallels 
        group: parallels 
        mode: 0644

    - name: 'copy index.html'
      copy:
        src: index.html
        dest: /home/parallels/exercice3/index.html
        owner: parallels 
        group: parallels 
        mode: 0644
    
    - name: 'build docker image'
      shell: docker build -t myapache_mbmk /home/parallels/exercice3

    - name: 'run docker container'
      shell: docker run -d -p 80:80 --name myapache_mbmk myapache_mbmk